{{ config(
    schema='BLACKPURL_PRODUCTION',
    materialized='incremental',
    incremental_strategy='merge',
    unique_key=['ORDER_NUMBER', 'INVOICE_DATE', 'JOB', 'TECHNICIAN'],
    pre_hook=[
        "{{ delete_duplicates_service_jobs('blackpurl_production', 'service_jobs_stage', 'temp_service_jobs_stage_table') }}",
        "{{ delete_duplicates_service_jobs('blackpurl_production_blackpurl_production', 'service_jobs_prod', 'temp_service_jobs_prod_table') }}",
    ],

    post_hook="TRUNCATE TABLE {{ source('blackpurl_production', 'service_jobs_stage') }};"

) }}


WITH stage AS (
    SELECT 
    _FILE,
    _LINE,
    _MODIFIED,
    TYPE,
    ORDER_NUMBER,
    CUSTOMER,
    JOB_TYPE,
    STATUS,
    SO_STATUS,
    JOB,
    UNIT_DESCRIPTION,
    TECHNICIAN,
    TRY_CAST(REPLACE(REPLACE(TOTAL, '$', ''), ',', '') AS FLOAT) as TOTAL,
    OPENED,
    MODIFIED,
    CONCERN,
    VIN,
    ENGINE_NUMBER,
    UNIT_NUMBER,
    SCHEDULED,
    COALESCE(TRY_TO_DATE(INVOICE_DATE, 'MM/DD/YYYY'), 
                TRY_TO_DATE(INVOICE_DATE, 'M/D/YYYY'), 
                TRY_TO_DATE(INVOICE_DATE, 'MM-DD-YYYY'), 
                TRY_TO_DATE(INVOICE_DATE, 'M-D-YYYY'), 
                TRY_TO_DATE(INVOICE_DATE, 'YYYY-MM-DD'),
                TRY_TO_DATE(INVOICE_DATE, 'MM/DD/YYYY HH24:MI'),
                TRY_TO_DATE(INVOICE_DATE, 'MM/DD/YYYY HH12:MI AM')) 
        AS formatted_date,
    INVOICE_NUMBER,
    HRS_BILLED,
    HRS_LOGGED,
    TRY_CAST(REPLACE(REPLACE(PARTS_TOTAL, '$', ''), ',', '') AS FLOAT) as PARTS_TOTAL,
    TRY_CAST(REPLACE(REPLACE(LABOR_TOTAL, '$', ''), ',', '') AS FLOAT) as LABOR_TOTAL,
    TRY_CAST(REPLACE(REPLACE(SUBLET_TOTAL, '$', ''), ',', '') AS FLOAT) as SUBLET_TOTAL,
    TRY_CAST(REPLACE(REPLACE(FEES_TOTAL, '$', ''), ',', '') AS FLOAT) as FEES_TOTAL,
    TRY_CAST(REPLACE(REPLACE(TAX_TOTAL, '$', ''), ',', '') AS FLOAT) as TAX_TOTAL,
    TRY_CAST(REPLACE(REPLACE(WIP_PART_COST, '$', ''), ',', '') AS FLOAT) as WIP_PART_COST,
    TRY_CAST(REPLACE(REPLACE(WIP_LABOR_COST, '$', ''), ',', '') AS FLOAT) as WIP_LABOR_COST,
    ODOMETER_IN,
    ODOMETER_OUT,
    SO_TYPE,
    MAKE,
    MODEL,
    SUB_MODEL,
    FIRST_NAME,
    LAST_NAME,
    ADDRESS,
    CITY,
    STATE,
    POSTAL,
    PHONE,
    MOBILE,
    EMAIL,
    OTHER_EMAIL,
    SALESPERSON,
    DATE_DUE_IN,
    DATE_PROMISED,
    UNIT_ARRIVED,
    _FIVETRAN_SYNCED
    FROM {{ source('blackpurl_production', 'service_jobs_stage') }}
    where formatted_date is not null
),

prod AS ( 
    SELECT 
    _FILE,
    _LINE,
    _MODIFIED,
    TYPE,
    ORDER_NUMBER,
    CUSTOMER,
    JOB_TYPE,
    STATUS,
    SO_STATUS,
    JOB,
    UNIT_DESCRIPTION,
    TECHNICIAN,
    TRY_CAST(REPLACE(REPLACE(TOTAL, '$', ''), ',', '') AS FLOAT) as TOTAL,
    OPENED,
    MODIFIED,
    CONCERN,
    VIN,
    ENGINE_NUMBER,
    UNIT_NUMBER,
    SCHEDULED,
    COALESCE(TRY_TO_DATE(INVOICE_DATE, 'MM/DD/YYYY'), 
                TRY_TO_DATE(INVOICE_DATE, 'M/D/YYYY'), 
                TRY_TO_DATE(INVOICE_DATE, 'MM-DD-YYYY'), 
                TRY_TO_DATE(INVOICE_DATE, 'M-D-YYYY'), 
                TRY_TO_DATE(INVOICE_DATE, 'YYYY-MM-DD'),
                TRY_TO_DATE(INVOICE_DATE, 'MM/DD/YYYY HH24:MI'),
                TRY_TO_DATE(INVOICE_DATE, 'MM/DD/YYYY HH12:MI AM')) 
        AS formatted_date,
    INVOICE_NUMBER,
    HRS_BILLED,
    HRS_LOGGED,
    TRY_CAST(REPLACE(REPLACE(PARTS_TOTAL, '$', ''), ',', '') AS FLOAT) as PARTS_TOTAL,
    TRY_CAST(REPLACE(REPLACE(LABOR_TOTAL, '$', ''), ',', '') AS FLOAT) as LABOR_TOTAL,
    TRY_CAST(REPLACE(REPLACE(SUBLET_TOTAL, '$', ''), ',', '') AS FLOAT) as SUBLET_TOTAL,
    TRY_CAST(REPLACE(REPLACE(FEES_TOTAL, '$', ''), ',', '') AS FLOAT) as FEES_TOTAL,
    TRY_CAST(REPLACE(REPLACE(TAX_TOTAL, '$', ''), ',', '') AS FLOAT) as TAX_TOTAL,
    TRY_CAST(REPLACE(REPLACE(WIP_PART_COST, '$', ''), ',', '') AS FLOAT) as WIP_PART_COST,
    TRY_CAST(REPLACE(REPLACE(WIP_LABOR_COST, '$', ''), ',', '') AS FLOAT) as WIP_LABOR_COST,
    ODOMETER_IN,
    ODOMETER_OUT,
    SO_TYPE,
    MAKE,
    MODEL,
    SUB_MODEL,
    FIRST_NAME,
    LAST_NAME,
    ADDRESS,
    CITY,
    STATE,
    POSTAL,
    PHONE,
    MOBILE,
    EMAIL,
    OTHER_EMAIL,
    SALESPERSON,
    DATE_DUE_IN,
    DATE_PROMISED,
    UNIT_ARRIVED,
    _FIVETRAN_SYNCED
    FROM {{ source('blackpurl_production_blackpurl_production', 'service_jobs_prod') }}
    where formatted_date is not null
),

matched_records AS (
    SELECT
        stage.*
    FROM stage
    JOIN prod
        ON stage.ORDER_NUMBER = prod.ORDER_NUMBER
        AND stage.formatted_date = prod.formatted_date
        AND stage.JOB = prod.JOB
        AND stage.TECHNICIAN = prod.TECHNICIAN
),

updates AS (
    SELECT
    matched_records._FILE,
    matched_records._LINE,
    matched_records._MODIFIED,
    matched_records.TYPE,
    matched_records.ORDER_NUMBER,
    matched_records.CUSTOMER,
    matched_records.JOB_TYPE,
    matched_records.STATUS,
    matched_records.SO_STATUS,
    matched_records.JOB,
    matched_records.UNIT_DESCRIPTION,
    matched_records.TECHNICIAN,
    matched_records.TOTAL,
    matched_records.OPENED,
    matched_records.MODIFIED,
    matched_records.CONCERN,
    matched_records.VIN,
    matched_records.ENGINE_NUMBER,
    matched_records.UNIT_NUMBER,
    matched_records.SCHEDULED,
    matched_records.formatted_date as INVOICE_DATE,
    matched_records.INVOICE_NUMBER,
    matched_records.HRS_BILLED,
    matched_records.HRS_LOGGED,
    matched_records.PARTS_TOTAL,
    matched_records.LABOR_TOTAL,
    matched_records.SUBLET_TOTAL,
    matched_records.FEES_TOTAL,
    matched_records.TAX_TOTAL,
    matched_records.WIP_PART_COST,
    matched_records.WIP_LABOR_COST,
    matched_records.ODOMETER_IN,
    matched_records.ODOMETER_OUT,
    matched_records.SO_TYPE,
    matched_records.MAKE,
    matched_records.MODEL,
    matched_records.SUB_MODEL,
    matched_records.FIRST_NAME,
    matched_records.LAST_NAME,
    matched_records.ADDRESS,
    matched_records.CITY,
    matched_records.STATE,
    matched_records.POSTAL,
    matched_records.PHONE,
    matched_records.MOBILE,
    matched_records.EMAIL,
    matched_records.OTHER_EMAIL,
    matched_records.SALESPERSON,
    matched_records.DATE_DUE_IN,
    matched_records.DATE_PROMISED,
    matched_records.UNIT_ARRIVED,
    matched_records._FIVETRAN_SYNCED
    FROM matched_records),

non_matched_records AS (
    SELECT
        stage.*
    FROM stage
    LEFT JOIN prod
        ON stage.INVOICE_NUMBER = prod.INVOICE_NUMBER
        AND stage.formatted_date = prod.formatted_date
        AND stage.JOB = prod.JOB
        AND stage.TECHNICIAN = prod.TECHNICIAN
    WHERE prod.INVOICE_NUMBER IS NULL AND prod.formatted_date IS NULL AND prod.JOB IS NULL AND prod.TECHNICIAN IS NULL
),

inserts AS (
    SELECT
    non_matched_records._FILE,
    non_matched_records._LINE,
    non_matched_records._MODIFIED,
    non_matched_records.TYPE,
    non_matched_records.ORDER_NUMBER,
    non_matched_records.CUSTOMER,
    non_matched_records.JOB_TYPE,
    non_matched_records.STATUS,
    non_matched_records.SO_STATUS,
    non_matched_records.JOB,
    non_matched_records.UNIT_DESCRIPTION,
    non_matched_records.TECHNICIAN,
    non_matched_records.TOTAL,
    non_matched_records.OPENED,
    non_matched_records.MODIFIED,
    non_matched_records.CONCERN,
    non_matched_records.VIN,
    non_matched_records.ENGINE_NUMBER,
    non_matched_records.UNIT_NUMBER,
    non_matched_records.SCHEDULED,
    non_matched_records.formatted_date as INVOICE_DATE,
    non_matched_records.INVOICE_NUMBER,
    non_matched_records.HRS_BILLED,
    non_matched_records.HRS_LOGGED,
    non_matched_records.PARTS_TOTAL,
    non_matched_records.LABOR_TOTAL,
    non_matched_records.SUBLET_TOTAL,
    non_matched_records.FEES_TOTAL,
    non_matched_records.TAX_TOTAL,
    non_matched_records.WIP_PART_COST,
    non_matched_records.WIP_LABOR_COST,
    non_matched_records.ODOMETER_IN,
    non_matched_records.ODOMETER_OUT,
    non_matched_records.SO_TYPE,
    non_matched_records.MAKE,
    non_matched_records.MODEL,
    non_matched_records.SUB_MODEL,
    non_matched_records.FIRST_NAME,
    non_matched_records.LAST_NAME,
    non_matched_records.ADDRESS,
    non_matched_records.CITY,
    non_matched_records.STATE,
    non_matched_records.POSTAL,
    non_matched_records.PHONE,
    non_matched_records.MOBILE,
    non_matched_records.EMAIL,
    non_matched_records.OTHER_EMAIL,
    non_matched_records.SALESPERSON,
    non_matched_records.DATE_DUE_IN,
    non_matched_records.DATE_PROMISED,
    non_matched_records.UNIT_ARRIVED,
    non_matched_records._FIVETRAN_SYNCED
    FROM non_matched_records)



SELECT
    _FILE,
    _LINE,
    _MODIFIED,
    TYPE,
    ORDER_NUMBER,
    CUSTOMER,
    JOB_TYPE,
    STATUS,
    SO_STATUS,
    JOB,
    UNIT_DESCRIPTION,
    TECHNICIAN,
    TOTAL,
    OPENED,
    MODIFIED,
    CONCERN,
    VIN,
    ENGINE_NUMBER,
    UNIT_NUMBER,
    SCHEDULED,
    INVOICE_DATE,
    INVOICE_NUMBER,
    HRS_BILLED,
    HRS_LOGGED,
    PARTS_TOTAL,
    LABOR_TOTAL,
    SUBLET_TOTAL,
    FEES_TOTAL,
    TAX_TOTAL,
    WIP_PART_COST,
    WIP_LABOR_COST,
    ODOMETER_IN,
    ODOMETER_OUT,
    SO_TYPE,
    MAKE,
    MODEL,
    SUB_MODEL,
    FIRST_NAME,
    LAST_NAME,
    ADDRESS,
    CITY,
    STATE,
    POSTAL,
    PHONE,
    MOBILE,
    EMAIL,
    OTHER_EMAIL,
    SALESPERSON,
    DATE_DUE_IN,
    DATE_PROMISED,
    UNIT_ARRIVED,
    _FIVETRAN_SYNCED
FROM updates

UNION

SELECT
    _FILE,
    _LINE,
    _MODIFIED,
    TYPE,
    ORDER_NUMBER,
    CUSTOMER,
    JOB_TYPE,
    STATUS,
    SO_STATUS,
    JOB,
    UNIT_DESCRIPTION,
    TECHNICIAN,
    TOTAL,
    OPENED,
    MODIFIED,
    CONCERN,
    VIN,
    ENGINE_NUMBER,
    UNIT_NUMBER,
    SCHEDULED,
    INVOICE_DATE,
    INVOICE_NUMBER,
    HRS_BILLED,
    HRS_LOGGED,
    PARTS_TOTAL,
    LABOR_TOTAL,
    SUBLET_TOTAL,
    FEES_TOTAL,
    TAX_TOTAL,
    WIP_PART_COST,
    WIP_LABOR_COST,
    ODOMETER_IN,
    ODOMETER_OUT,
    SO_TYPE,
    MAKE,
    MODEL,
    SUB_MODEL,
    FIRST_NAME,
    LAST_NAME,
    ADDRESS,
    CITY,
    STATE,
    POSTAL,
    PHONE,
    MOBILE,
    EMAIL,
    OTHER_EMAIL,
    SALESPERSON,
    DATE_DUE_IN,
    DATE_PROMISED,
    UNIT_ARRIVED,
    _FIVETRAN_SYNCED
FROM inserts