{% macro delete_duplicates_deal_units(schema, table_name, temp_table_name) %}

-- Create a temporary table with distinct values and row numbers
CREATE TEMPORARY TABLE {{ temp_table_name }} AS
SELECT 
    _FILE,
    _LINE,
    _MODIFIED,
    TYPE,
    STOCK_NUMBER,
    MAKE,
    MODEL,
    SUBMODEL,
    YEAR,
    STATUS,
    ORDER_NUMBER,
    TOTAL_PRICE,
    DEAL_TYPE,
    CUSTOMER,
    DATE_SOLD,
    BASE_PRICE,
    FACTORY_OPTIONS,
    DEALER_INSTALLED,
    PART_OPTIONS,
    LABOR_OPTIONS,
    SUBLET_OPTIONS,
    FEE_OPTIONS,
    WARRANTY_OPTIONS,
    OTHER_PRODUCTS,
    STAMP_DUTY,
    VIN,
    NEW_UNIT,
    CATEGORY,
    STOCKED_IN,
    AGE,
    TAGS,
    MILEAGE,
    MILEAGE_TYPE,
    EXT_COLOR,
    FIRST_NAME,
    LAST_NAME,
    ADDRESS,
    CITY,
    STATE,
    POSTAL,
    PHONE,
    MOBILE,
    EMAIL,
    OTHER_EMAIL,
    SALESPERSON,
    GVWR,
    DESCRIPTION,
    _FIVETRAN_SYNCED,
    ROW_NUMBER() OVER (PARTITION BY STOCK_NUMBER, ORDER_NUMBER ORDER BY _MODIFIED DESC) AS row_num
FROM {{ source(schema, table_name) }};

-- Truncate the original table
TRUNCATE TABLE {{ source(schema, table_name) }};

-- Insert the records from the temporary table back into the main table, selecting only the most recent rows
INSERT INTO {{ source(schema, table_name) }} 
        (_FILE,
    _LINE,
    _MODIFIED,
    TYPE,
    STOCK_NUMBER,
    MAKE,
    MODEL,
    SUBMODEL,
    YEAR,
    STATUS,
    ORDER_NUMBER,
    TOTAL_PRICE,
    DEAL_TYPE,
    CUSTOMER,
    DATE_SOLD,
    BASE_PRICE,
    FACTORY_OPTIONS,
    DEALER_INSTALLED,
    PART_OPTIONS,
    LABOR_OPTIONS,
    SUBLET_OPTIONS,
    FEE_OPTIONS,
    WARRANTY_OPTIONS,
    OTHER_PRODUCTS,
    STAMP_DUTY,
    VIN,
    NEW_UNIT,
    CATEGORY,
    STOCKED_IN,
    AGE,
    TAGS,
    MILEAGE,
    MILEAGE_TYPE,
    EXT_COLOR,
    FIRST_NAME,
    LAST_NAME,
    ADDRESS,
    CITY,
    STATE,
    POSTAL,
    PHONE,
    MOBILE,
    EMAIL,
    OTHER_EMAIL,
    SALESPERSON,
    GVWR,
    DESCRIPTION,
    _FIVETRAN_SYNCED)

SELECT 
    _FILE,
    _LINE,
    _MODIFIED,
    TYPE,
    STOCK_NUMBER,
    MAKE,
    MODEL,
    SUBMODEL,
    YEAR,
    STATUS,
    ORDER_NUMBER,
    TOTAL_PRICE,
    DEAL_TYPE,
    CUSTOMER,
    DATE_SOLD,
    BASE_PRICE,
    FACTORY_OPTIONS,
    DEALER_INSTALLED,
    PART_OPTIONS,
    LABOR_OPTIONS,
    SUBLET_OPTIONS,
    FEE_OPTIONS,
    WARRANTY_OPTIONS,
    OTHER_PRODUCTS,
    STAMP_DUTY,
    VIN,
    NEW_UNIT,
    CATEGORY,
    STOCKED_IN,
    AGE,
    TAGS,
    MILEAGE,
    MILEAGE_TYPE,
    EXT_COLOR,
    FIRST_NAME,
    LAST_NAME,
    ADDRESS,
    CITY,
    STATE,
    POSTAL,
    PHONE,
    MOBILE,
    EMAIL,
    OTHER_EMAIL,
    SALESPERSON,
    GVWR,
    DESCRIPTION,
    _FIVETRAN_SYNCED
FROM {{ temp_table_name }}
WHERE row_num = 1;

-- Drop the temporary table
DROP TABLE {{ temp_table_name }};

{% endmacro %}