{% macro delete_duplicates_service_jobs(schema, table_name, temp_table_name) %}

-- Create a temporary table with distinct values and row numbers
CREATE TEMPORARY TABLE {{ temp_table_name }} AS
SELECT 
    _FILE,
    _LINE,
    _MODIFIED,
    TYPE,
    ORDER_NUMBER,
    CUSTOMER,
    JOB_TYPE,
    STATUS,
    SO_STATUS,
    JOB,
    UNIT_DESCRIPTION,
    TECHNICIAN,
    TOTAL,
    OPENED,
    MODIFIED,
    CONCERN,
    VIN,
    ENGINE_NUMBER,
    UNIT_NUMBER,
    SCHEDULED,
    INVOICE_DATE,
    INVOICE_NUMBER,
    HRS_BILLED,
    HRS_LOGGED,
    PARTS_TOTAL,
    LABOR_TOTAL,
    SUBLET_TOTAL,
    FEES_TOTAL,
    TAX_TOTAL,
    WIP_PART_COST,
    WIP_LABOR_COST,
    ODOMETER_IN,
    ODOMETER_OUT,
    SO_TYPE,
    MAKE,
    MODEL,
    SUB_MODEL,
    FIRST_NAME,
    LAST_NAME,
    ADDRESS,
    CITY,
    STATE,
    POSTAL,
    PHONE,
    MOBILE,
    EMAIL,
    OTHER_EMAIL,
    SALESPERSON,
    DATE_DUE_IN,
    DATE_PROMISED,
    UNIT_ARRIVED,
    _FIVETRAN_SYNCED,
    ROW_NUMBER() OVER (PARTITION BY ORDER_NUMBER, INVOICE_DATE, JOB, TECHNICIAN ORDER BY _MODIFIED DESC) AS row_num
FROM {{ source(schema, table_name) }};

-- Truncate the original table
TRUNCATE TABLE {{ source(schema, table_name) }};

-- Insert the records from the temporary table back into the main table, selecting only the most recent rows
INSERT INTO {{ source(schema, table_name) }} 
        (_FILE,
    _LINE,
    _MODIFIED,
    TYPE,
    ORDER_NUMBER,
    CUSTOMER,
    JOB_TYPE,
    STATUS,
    SO_STATUS,
    JOB,
    UNIT_DESCRIPTION,
    TECHNICIAN,
    TOTAL,
    OPENED,
    MODIFIED,
    CONCERN,
    VIN,
    ENGINE_NUMBER,
    UNIT_NUMBER,
    SCHEDULED,
    INVOICE_DATE,
    INVOICE_NUMBER,
    HRS_BILLED,
    HRS_LOGGED,
    PARTS_TOTAL,
    LABOR_TOTAL,
    SUBLET_TOTAL,
    FEES_TOTAL,
    TAX_TOTAL,
    WIP_PART_COST,
    WIP_LABOR_COST,
    ODOMETER_IN,
    ODOMETER_OUT,
    SO_TYPE,
    MAKE,
    MODEL,
    SUB_MODEL,
    FIRST_NAME,
    LAST_NAME,
    ADDRESS,
    CITY,
    STATE,
    POSTAL,
    PHONE,
    MOBILE,
    EMAIL,
    OTHER_EMAIL,
    SALESPERSON,
    DATE_DUE_IN,
    DATE_PROMISED,
    UNIT_ARRIVED,
    _FIVETRAN_SYNCED)

SELECT 
    _FILE,
    _LINE,
    _MODIFIED,
    TYPE,
    ORDER_NUMBER,
    CUSTOMER,
    JOB_TYPE,
    STATUS,
    SO_STATUS,
    JOB,
    UNIT_DESCRIPTION,
    TECHNICIAN,
    TOTAL,
    OPENED,
    MODIFIED,
    CONCERN,
    VIN,
    ENGINE_NUMBER,
    UNIT_NUMBER,
    SCHEDULED,
    INVOICE_DATE,
    INVOICE_NUMBER,
    HRS_BILLED,
    HRS_LOGGED,
    PARTS_TOTAL,
    LABOR_TOTAL,
    SUBLET_TOTAL,
    FEES_TOTAL,
    TAX_TOTAL,
    WIP_PART_COST,
    WIP_LABOR_COST,
    ODOMETER_IN,
    ODOMETER_OUT,
    SO_TYPE,
    MAKE,
    MODEL,
    SUB_MODEL,
    FIRST_NAME,
    LAST_NAME,
    ADDRESS,
    CITY,
    STATE,
    POSTAL,
    PHONE,
    MOBILE,
    EMAIL,
    OTHER_EMAIL,
    SALESPERSON,
    DATE_DUE_IN,
    DATE_PROMISED,
    UNIT_ARRIVED,
    _FIVETRAN_SYNCED
FROM {{ temp_table_name }}
WHERE row_num = 1;

-- Drop the temporary table
DROP TABLE {{ temp_table_name }};

{% endmacro %}